[package]
name = "socketeer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.9.0"
futures = "0.3.31"
futures-util = "0.3.31"
rustls = { version = "0.23.20", features = ["ring"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.8"
tokio-tungstenite = { version = "0.26", features = ["rustls-tls-webpki-roots"] }
tokio = { version = "1.42.0", default-features = false, features = [
    "net",
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
    "tracing",
] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
url = "2.5.4"
