[package]
name = "socketeer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
futures = "0.3"
futures-util = "0.3"
rustls = { version = "0.23", features = ["ring"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio-tungstenite = { version = "0.26", features = ["rustls-tls-webpki-roots"] }
tokio = { version = "1", default-features = false, features = [
    "net",
    "macros",
    "rt",
    "sync",
] }
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2"

[profile.dev]
tokio = { version = "1", default-features = false, features = [
    "net",
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
    "tracing",
] }
